name: Birdnet-go Proxy
version: "0.1"
panel_title: birdnet-go Proxy Addon
slug: birdnet-go-proxy
description: birdnet-go proxy addon for Home Assistant
url: "https://github.com/jasonmadigan/birdnet-go-proxy"
startup: application
boot: auto
webui: "http://[HOST]:[PORT:8080]/"
watchdog: "http://[HOST]:[PORT:4003]/"
ingress: true
ingress_port: 4003
ingress_entry: ""
panel_admin: false
ports:
  4003/tcp: 4003
ports_description:
  4003/tcp: Web interface (Not required for Hass.io Ingress)
host_network: false
devices: []
usb: false
tmpfs: false
full_access: false
environment: {}
options:
  server: "http://192.168.1.230:8080"
  proxy_pass_host: true
  proxy_pass_real_ip: true
schema:
  server: "match(^https?://.+:\\d+$)"
  proxy_pass_host: bool
  proxy_pass_real_ip: bool
services: []
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map: []
